### ISSUE TITLE
clear curl options

### ISSUE THREAD

**Issue by dansmith65** [nickorr/BaseElements-Plugin#79]
`BE_Curl_Set_Option ( "" ; "" )` does seem to reset the options, but `BE_GetLastError` returns `11` after calling it.

**Comment by nickorr** [comment]
Expected behaviour.  There is no empty string curl option, so you can't set a value for it.  Use it like this : 

The usage is

	BE_Curl_Set_Option ( "CURLOPT_HTTPAUTH" ; 1 )

to set the option.


	BE_Curl_Set_Option ( "CURLOPT_HTTPAUTH” )

to clear the option and

	BE_Curl_Set_Option

to clear all options.  I've updated the docs : https://github.com/nickorr/BaseElements-Plugin/wiki/Functions#BE_Curl_Set_Option

Cheers,
Nick

**Comment by dansmith65** [comment]
Thanks for updating the docs, there was still a reference to using `BE_Curl_Set_Option ( "" ; "" )` to reset to default, so I modified the wiki to reflect what you just mentioned.

**Comment by nickorr** [comment]
Awesome, thanks.
